using System.Collections.Generic;
using System.Linq;
using BTCPayServer.Plugins.OpenPatron.Controllers;
using BTCPayServer.Plugins.OpenPatron.Models;
using BTCPayServer.Plugins.OpenPatron.Services;
using BTCPayServer.Data.Subscriptions;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Xunit;

namespace BTCPayServer.Plugins.OpenPatron.Tests;

[Trait("Fast", "Fast")]
public class FastTests
{
    // ── Original model-default tests ──

    [Fact]
    public void OpenPatronSettingsDefaultsToUnpublished()
    {
        var settings = new OpenPatronAppSettings();

        Assert.Equal(OpenPatronVisibility.Unpublished, settings.Visibility);
        Assert.Equal(OpenPatronSupportMode.Both, settings.SupportMode);
        Assert.Null(settings.OfferingId);
        Assert.Empty(settings.SuggestedAmounts);
    }

    [Fact]
    public void DefaultPageTypeIsProject()
    {
        var settings = new OpenPatronAppSettings();
        Assert.Equal(OpenPatronPageType.Project, settings.PageType);
        Assert.False(settings.PageTypeConfirmed);
    }

    [Fact]
    public void AccentColorDefaultIsNull()
    {
        var settings = new OpenPatronAppSettings();
        Assert.Null(settings.AccentColor);
    }

    [Fact]
    public void SponsorWallDefaultDisabled()
    {
        var settings = new OpenPatronAppSettings();
        Assert.False(settings.ShowSponsorWall);
    }

    [Fact]
    public void SocialLinksDefaultNull()
    {
        var settings = new OpenPatronAppSettings();
        Assert.Null(settings.SocialLinks);
    }

    [Fact]
    public void FundingGoalDefaultNull()
    {
        var settings = new OpenPatronAppSettings();
        Assert.Null(settings.FundingGoal);
    }

    [Fact]
    public void GravatarUrlIsComputedFromEmail()
    {
        var url = UIOpenPatronController.ComputeGravatarUrl("test@example.com");
        Assert.NotNull(url);
        Assert.StartsWith("https://www.gravatar.com/avatar/", url);
        Assert.Contains("s=200", url);
        Assert.Contains("55502f40dc8b7c769880b10874abc9d0", url);
    }

    [Fact]
    public void GravatarUrlIsNullForEmptyEmail()
    {
        Assert.Null(UIOpenPatronController.ComputeGravatarUrl(null));
        Assert.Null(UIOpenPatronController.ComputeGravatarUrl(""));
        Assert.Null(UIOpenPatronController.ComputeGravatarUrl("   "));
    }

    [Fact]
    public void Md5HashIsCorrect()
    {
        var hash = UIOpenPatronController.ComputeMd5Hash("hello");
        Assert.Equal("5d41402abc4b2a76b9719d911017c592", hash);
    }

    [Fact]
    public void ProjectsListDefaultEmpty()
    {
        var settings = new OpenPatronAppSettings();
        Assert.Empty(settings.Projects);
    }

    [Fact]
    public void OfferingResolverPrefersRicherOfferingOverEmptyPreferred()
    {
        var richer = new OfferingData
        {
            Id = "offering-rich",
            CreatedAt = new(2026, 4, 23, 20, 0, 0, System.TimeSpan.Zero),
            Plans = [new PlanData()],
            Features = []
        };
        var emptyPreferred = new OfferingData
        {
            Id = "offering-empty",
            CreatedAt = new(2026, 4, 23, 21, 0, 0, System.TimeSpan.Zero),
            Plans = [],
            Features = []
        };

        var selected = OpenPatronOfferingResolver.SelectPreferredOffering([richer, emptyPreferred], emptyPreferred.Id);

        Assert.Equal(richer.Id, selected?.Id);
    }

    [Fact]
    public void OfferingResolverKeepsPreferredOfferingWhenItHasPlans()
    {
        var olderPreferred = new OfferingData
        {
            Id = "offering-preferred",
            CreatedAt = new(2026, 4, 23, 20, 0, 0, System.TimeSpan.Zero),
            Plans = [new PlanData()],
            Features = []
        };
        var newerEmpty = new OfferingData
        {
            Id = "offering-empty",
            CreatedAt = new(2026, 4, 23, 21, 0, 0, System.TimeSpan.Zero),
            Plans = [],
            Features = []
        };

        var selected = OpenPatronOfferingResolver.SelectPreferredOffering([olderPreferred, newerEmpty], olderPreferred.Id);

        Assert.Equal(olderPreferred.Id, selected?.Id);
    }

    // ── BlockDefinition model tests ──

    [Fact]
    public void BlockDefinitionHasAutoGeneratedId()
    {
        var block = new BlockDefinition();
        Assert.NotNull(block.Id);
        Assert.Equal(12, block.Id.Length);
    }

    [Fact]
    public void BlockDefinitionDefaultTypeIsEmpty()
    {
        var block = new BlockDefinition();
        Assert.Equal(string.Empty, block.Type);
    }

    [Fact]
    public void BlockDefinitionSettingsDefaultNull()
    {
        var block = new BlockDefinition();
        Assert.Null(block.Settings);
    }

    [Fact]
    public void TwoBlockDefinitionsHaveDifferentIds()
    {
        var a = new BlockDefinition();
        var b = new BlockDefinition();
        Assert.NotEqual(a.Id, b.Id);
    }

    // ── PageTheme model tests ──

    [Fact]
    public void PageThemeDefaults()
    {
        var theme = new PageTheme();
        Assert.Equal("#6366f1", theme.AccentColor);
        Assert.Equal("1.5rem", theme.BorderRadius);
        Assert.Equal("1rem", theme.BlockSpacing);
    }

    // ── BlockRegistry tests ──

    [Fact]
    public void BlockRegistryReturnsPathForKnownTypes()
    {
        Assert.NotNull(BlockRegistry.GetPartialViewPath("profile-hero"));
        Assert.NotNull(BlockRegistry.GetPartialViewPath("project-hero"));
        Assert.NotNull(BlockRegistry.GetPartialViewPath("funding-progress"));
        Assert.NotNull(BlockRegistry.GetPartialViewPath("description"));
        Assert.NotNull(BlockRegistry.GetPartialViewPath("projects-grid"));
        Assert.NotNull(BlockRegistry.GetPartialViewPath("subscription-tiers"));
        Assert.NotNull(BlockRegistry.GetPartialViewPath("quick-support"));
        Assert.NotNull(BlockRegistry.GetPartialViewPath("sponsor-wall"));
    }

    [Fact]
    public void BlockRegistryReturnsNullForUnknownType()
    {
        Assert.Null(BlockRegistry.GetPartialViewPath("nonexistent-block"));
    }

    [Fact]
    public void BlockRegistryIsKnownTypeIsCaseInsensitive()
    {
        Assert.True(BlockRegistry.IsKnownType("Profile-Hero"));
        Assert.True(BlockRegistry.IsKnownType("PROFILE-HERO"));
        Assert.True(BlockRegistry.IsKnownType("profile-hero"));
    }

    [Fact]
    public void AllBlockTypesHavePartialViewPaths()
    {
        foreach (var (type, info) in BlockRegistry.AllTypes)
        {
            Assert.False(string.IsNullOrWhiteSpace(info.PartialViewPath), $"Block type '{type}' has no partial view path.");
            Assert.True(info.PartialViewPath.EndsWith(".cshtml"), $"Block type '{type}' partial path doesn't end with .cshtml");
        }
    }

    // ── Default layout tests ──

    [Fact]
    public void DefaultPersonalLayoutHasExpectedBlocks()
    {
        var layout = BlockRegistry.DefaultLayoutForPersonal();
        var types = layout.Select(b => b.Type).ToList();

        Assert.Equal(
            new[] { "profile-hero", "funding-progress", "description", "projects-grid", "subscription-tiers", "quick-support", "sponsor-wall" },
            types);
    }

    [Fact]
    public void DefaultProjectLayoutHasExpectedBlocks()
    {
        var layout = BlockRegistry.DefaultLayoutForProject();
        var types = layout.Select(b => b.Type).ToList();

        Assert.Equal(
            new[] { "project-hero", "funding-progress", "description", "subscription-tiers", "quick-support", "sponsor-wall" },
            types);
    }

    [Fact]
    public void DefaultLayoutForDelegatesCorrectly()
    {
        var personal = BlockRegistry.DefaultLayoutFor(OpenPatronPageType.Personal);
        var project = BlockRegistry.DefaultLayoutFor(OpenPatronPageType.Project);

        Assert.Equal("profile-hero", personal[0].Type);
        Assert.Equal("project-hero", project[0].Type);
    }

    [Fact]
    public void DefaultLayoutBlocksHaveUniqueIds()
    {
        var layout = BlockRegistry.DefaultLayoutForPersonal();
        var ids = layout.Select(b => b.Id).ToList();
        Assert.Equal(ids.Count, ids.Distinct().Count());
    }

    // ── EnsurePageLayout tests ──

    [Fact]
    public void EnsurePageLayoutStartsEmptyForOldPages()
    {
        var settings = new OpenPatronAppSettings
        {
            PageType = OpenPatronPageType.Personal,
            PageTypeConfirmed = true,
            PageLayout = null
        };

        UIOpenPatronController.EnsurePageLayout(settings);

        Assert.NotNull(settings.PageLayout);
        Assert.Empty(settings.PageLayout!);
    }

    [Fact]
    public void EnsurePageLayoutDoesNotOverwriteExistingLayout()
    {
        var existingLayout = new List<BlockDefinition>
        {
            new() { Id = "custom1", Type = "description" }
        };
        var settings = new OpenPatronAppSettings
        {
            PageTypeConfirmed = true,
            PageLayout = existingLayout
        };

        UIOpenPatronController.EnsurePageLayout(settings);

        Assert.Single(settings.PageLayout!);
        Assert.Equal("custom1", settings.PageLayout![0].Id);
    }

    [Fact]
    public void EnsurePageLayoutCreatesDefaultThemeWhenNull()
    {
        var settings = new OpenPatronAppSettings
        {
            PageLayout = null,
            Theme = null
        };

        UIOpenPatronController.EnsurePageLayout(settings);

        Assert.NotNull(settings.Theme);
        Assert.Equal("#6366f1", settings.Theme!.AccentColor);
    }

    [Fact]
    public void EnsurePageLayoutPreservesExistingTheme()
    {
        var settings = new OpenPatronAppSettings
        {
            PageLayout = null,
            Theme = new PageTheme { AccentColor = "#ff0000" }
        };

        UIOpenPatronController.EnsurePageLayout(settings);

        Assert.Equal("#ff0000", settings.Theme!.AccentColor);
    }

    // ── JSON round-trip tests ──

    [Fact]
    public void BlockDefinitionJsonRoundTrip()
    {
        var block = new BlockDefinition
        {
            Id = "test123",
            Type = "profile-hero",
            Settings = JObject.FromObject(new { showAvatar = true, showBio = false })
        };

        var json = JsonConvert.SerializeObject(block);
        var deserialized = JsonConvert.DeserializeObject<BlockDefinition>(json);

        Assert.NotNull(deserialized);
        Assert.Equal("test123", deserialized!.Id);
        Assert.Equal("profile-hero", deserialized.Type);
        Assert.NotNull(deserialized.Settings);
        Assert.True(deserialized.Settings!["showAvatar"]!.Value<bool>());
        Assert.False(deserialized.Settings["showBio"]!.Value<bool>());
    }

    [Fact]
    public void BlockDefinitionWithNullSettingsSerializes()
    {
        var block = new BlockDefinition { Id = "abc", Type = "description", Settings = null };
        var json = JsonConvert.SerializeObject(block);
        var deserialized = JsonConvert.DeserializeObject<BlockDefinition>(json);

        Assert.NotNull(deserialized);
        Assert.Equal("description", deserialized!.Type);
        Assert.Null(deserialized.Settings);
    }

    [Fact]
    public void FullSettingsJsonRoundTrip()
    {
        var settings = new OpenPatronAppSettings
        {
            PageType = OpenPatronPageType.Personal,
            PageTypeConfirmed = true,
            PageLayout =
            [
                new() { Id = "b1", Type = "profile-hero" },
                new() { Id = "b2", Type = "description", Settings = JObject.FromObject(new { title = "About me" }) }
            ],
            Theme = new PageTheme { AccentColor = "#00ff00", BorderRadius = "2rem", BlockSpacing = "0.5rem" },
            DisplayName = "Jane",
            AccentColor = "#00ff00"
        };

        var json = JsonConvert.SerializeObject(settings);
        var deserialized = JsonConvert.DeserializeObject<OpenPatronAppSettings>(json);

        Assert.NotNull(deserialized);
        Assert.Equal(2, deserialized!.PageLayout!.Count);
        Assert.Equal("profile-hero", deserialized.PageLayout[0].Type);
        Assert.Equal("About me", deserialized.PageLayout[1].Settings!["title"]!.Value<string>());
        Assert.Equal("#00ff00", deserialized.Theme!.AccentColor);
        Assert.Equal("2rem", deserialized.Theme.BorderRadius);
        Assert.Equal("Jane", deserialized.DisplayName);
    }

    [Fact]
    public void PageLayoutNullDeserializesCorrectly()
    {
        var settings = new OpenPatronAppSettings { PageLayout = null };
        var json = JsonConvert.SerializeObject(settings);
        var deserialized = JsonConvert.DeserializeObject<OpenPatronAppSettings>(json);

        Assert.Null(deserialized!.PageLayout);
    }

    [Fact]
    public void BlockListOrderPreservedThroughSerialization()
    {
        var blocks = new List<BlockDefinition>
        {
            new() { Id = "1", Type = "sponsor-wall" },
            new() { Id = "2", Type = "profile-hero" },
            new() { Id = "3", Type = "description" },
        };

        var json = JsonConvert.SerializeObject(blocks);
        var deserialized = JsonConvert.DeserializeObject<List<BlockDefinition>>(json);

        Assert.Equal(3, deserialized!.Count);
        Assert.Equal("sponsor-wall", deserialized[0].Type);
        Assert.Equal("profile-hero", deserialized[1].Type);
        Assert.Equal("description", deserialized[2].Type);
    }
}
