using System.Collections.Generic;
using System.Linq;
using BTCPayServer.Plugins.OpenPatron.Controllers;
using BTCPayServer.Plugins.OpenPatron.Models;
using BTCPayServer.Plugins.OpenPatron.Services;
using BTCPayServer.Data.Subscriptions;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Xunit;

namespace BTCPayServer.Plugins.OpenPatron.Tests;

[Trait("Fast", "Fast")]
public class FastTests
{
    // ── Settings defaults ──

    [Fact]
    public void SettingsDefaultsToUnpublished()
    {
        var settings = new OpenPatronAppSettings();
        Assert.Equal(OpenPatronVisibility.Unpublished, settings.Visibility);
        Assert.Equal(OpenPatronSupportMode.Both, settings.SupportMode);
        Assert.Null(settings.OfferingId);
    }

    [Fact]
    public void DefaultPageTypeIsProject()
    {
        var settings = new OpenPatronAppSettings();
        Assert.Equal(OpenPatronPageType.Project, settings.PageType);
        Assert.False(settings.PageTypeConfirmed);
    }

    [Fact]
    public void PageLayoutDefaultNull()
    {
        var settings = new OpenPatronAppSettings();
        Assert.Null(settings.PageLayout);
    }

    // ── BlockDefinition ──

    [Fact]
    public void BlockDefinitionHasAutoGeneratedId()
    {
        var block = new BlockDefinition();
        Assert.NotNull(block.Id);
        Assert.Equal(12, block.Id.Length);
    }

    [Fact]
    public void TwoBlockDefinitionsHaveDifferentIds()
    {
        Assert.NotEqual(new BlockDefinition().Id, new BlockDefinition().Id);
    }

    [Fact]
    public void BlockDefinitionSettingsDefaultNull()
    {
        Assert.Null(new BlockDefinition().Settings);
    }

    // ── PageTheme ──

    [Fact]
    public void PageThemeDefaults()
    {
        var theme = new PageTheme();
        Assert.Equal("#6366f1", theme.AccentColor);
        Assert.Equal("1.5rem", theme.BorderRadius);
        Assert.Equal("1rem", theme.BlockSpacing);
    }

    // ── BlockRegistry ──

    [Fact]
    public void BlockRegistryReturnsPathForKnownTypes()
    {
        foreach (var type in new[] { "profile-hero", "project-hero", "funding-progress", "description", "projects-grid", "subscription-tiers", "quick-support", "sponsor-wall" })
        {
            Assert.NotNull(BlockRegistry.GetPartialViewPath(type));
        }
    }

    [Fact]
    public void BlockRegistryReturnsNullForUnknownType()
    {
        Assert.Null(BlockRegistry.GetPartialViewPath("nonexistent"));
    }

    [Fact]
    public void BlockRegistryIsCaseInsensitive()
    {
        Assert.True(BlockRegistry.IsKnownType("Profile-Hero"));
        Assert.True(BlockRegistry.IsKnownType("PROFILE-HERO"));
    }

    // ── Default layouts have Settings populated ──

    [Fact]
    public void DefaultPersonalLayoutHasExpectedBlocks()
    {
        var layout = BlockRegistry.DefaultLayoutForPersonal();
        var types = layout.Select(b => b.Type).ToList();
        Assert.Equal(
            new[] { "profile-hero", "funding-progress", "description", "projects-grid", "subscription-tiers", "quick-support", "sponsor-wall" },
            types);
    }

    [Fact]
    public void DefaultProjectLayoutHasExpectedBlocks()
    {
        var layout = BlockRegistry.DefaultLayoutForProject();
        var types = layout.Select(b => b.Type).ToList();
        Assert.Equal(
            new[] { "project-hero", "funding-progress", "description", "subscription-tiers", "quick-support", "sponsor-wall" },
            types);
    }

    [Fact]
    public void DefaultLayoutBlocksHaveSettings()
    {
        foreach (var block in BlockRegistry.DefaultLayoutForPersonal())
        {
            Assert.NotNull(block.Settings);
        }
        foreach (var block in BlockRegistry.DefaultLayoutForProject())
        {
            Assert.NotNull(block.Settings);
        }
    }

    [Fact]
    public void DefaultDescriptionBlockHasHeading()
    {
        var block = BlockRegistry.DefaultLayoutForProject().First(b => b.Type == "description");
        Assert.Equal("Why sponsor this work?", block.Settings!["heading"]!.ToString());
    }

    [Fact]
    public void DefaultLayoutBlocksHaveUniqueIds()
    {
        var layout = BlockRegistry.DefaultLayoutForPersonal();
        var ids = layout.Select(b => b.Id).ToList();
        Assert.Equal(ids.Count, ids.Distinct().Count());
    }

    // ── BlockSettingsHelper ──

    [Fact]
    public void HelperStrReadsString()
    {
        var obj = JObject.FromObject(new { name = "Jane" });
        Assert.Equal("Jane", BlockSettingsHelper.Str(obj, "name"));
    }

    [Fact]
    public void HelperStrReturnsNullForMissing()
    {
        var obj = new JObject();
        Assert.Null(BlockSettingsHelper.Str(obj, "missing"));
    }

    [Fact]
    public void HelperStrFallback()
    {
        var obj = new JObject();
        Assert.Equal("default", BlockSettingsHelper.Str(obj, "missing", "default"));
    }

    [Fact]
    public void HelperDecReadsNumber()
    {
        var obj = JObject.FromObject(new { goal = 1000m });
        Assert.Equal(1000m, BlockSettingsHelper.Dec(obj, "goal"));
    }

    [Fact]
    public void HelperDecReturnsNullForMissing()
    {
        Assert.Null(BlockSettingsHelper.Dec(new JObject(), "goal"));
    }

    [Fact]
    public void HelperDecArrayReadsAmounts()
    {
        var obj = JObject.FromObject(new { suggestedAmounts = new[] { 5m, 15m, 50m } });
        Assert.Equal(new[] { 5m, 15m, 50m }, BlockSettingsHelper.DecArray(obj, "suggestedAmounts"));
    }

    [Fact]
    public void HelperDecArrayReturnsEmptyForMissing()
    {
        Assert.Empty(BlockSettingsHelper.DecArray(new JObject(), "amounts"));
    }

    [Fact]
    public void HelperGravatarUrlWorks()
    {
        var obj = JObject.FromObject(new { gravatarEmail = "test@example.com" });
        var url = BlockSettingsHelper.GravatarUrl(obj);
        Assert.NotNull(url);
        Assert.StartsWith("https://www.gravatar.com/avatar/", url);
        Assert.Contains("55502f40dc8b7c769880b10874abc9d0", url);
    }

    [Fact]
    public void HelperGravatarUrlNullForMissing()
    {
        Assert.Null(BlockSettingsHelper.GravatarUrl(new JObject()));
    }

    [Fact]
    public void HelperGitHubProfileUrlWorks()
    {
        var obj = JObject.FromObject(new { gitHubUsername = "octocat" });
        Assert.Equal("https://github.com/octocat", BlockSettingsHelper.GitHubProfileUrl(obj));
    }

    [Fact]
    public void HelperGitHubProfileUrlNullForMissing()
    {
        Assert.Null(BlockSettingsHelper.GitHubProfileUrl(new JObject()));
    }

    [Fact]
    public void HelperHasSocialLinks()
    {
        Assert.False(BlockSettingsHelper.HasSocialLinks(new JObject()));
        Assert.True(BlockSettingsHelper.HasSocialLinks(JObject.FromObject(new { socialX = "handle" })));
    }

    // ── EnsurePageLayout ──

    [Fact]
    public void EnsurePageLayoutStartsEmpty()
    {
        var settings = new OpenPatronAppSettings { PageLayout = null };
        UIOpenPatronController.EnsurePageLayout(settings);
        Assert.NotNull(settings.PageLayout);
        Assert.Empty(settings.PageLayout!);
    }

    [Fact]
    public void EnsurePageLayoutDoesNotOverwrite()
    {
        var existing = new List<BlockDefinition> { new() { Id = "x", Type = "description" } };
        var settings = new OpenPatronAppSettings { PageLayout = existing };
        UIOpenPatronController.EnsurePageLayout(settings);
        Assert.Single(settings.PageLayout!);
        Assert.Equal("x", settings.PageLayout![0].Id);
    }

    [Fact]
    public void EnsurePageLayoutCreatesDefaultTheme()
    {
        var settings = new OpenPatronAppSettings { Theme = null };
        UIOpenPatronController.EnsurePageLayout(settings);
        Assert.NotNull(settings.Theme);
        Assert.Equal("#6366f1", settings.Theme!.AccentColor);
    }

    [Fact]
    public void EnsurePageLayoutPreservesExistingTheme()
    {
        var settings = new OpenPatronAppSettings { Theme = new PageTheme { AccentColor = "#ff0000" } };
        UIOpenPatronController.EnsurePageLayout(settings);
        Assert.Equal("#ff0000", settings.Theme!.AccentColor);
    }

    // ── JSON round-trip ──

    [Fact]
    public void BlockWithSettingsJsonRoundTrip()
    {
        var block = new BlockDefinition
        {
            Id = "test1",
            Type = "profile-hero",
            Settings = JObject.FromObject(new { displayName = "Jane", bio = "Hello world", socialX = "janedev" })
        };
        var json = JsonConvert.SerializeObject(block);
        var deserialized = JsonConvert.DeserializeObject<BlockDefinition>(json)!;
        Assert.Equal("test1", deserialized.Id);
        Assert.Equal("profile-hero", deserialized.Type);
        Assert.Equal("Jane", deserialized.Settings!["displayName"]!.ToString());
        Assert.Equal("janedev", deserialized.Settings["socialX"]!.ToString());
    }

    [Fact]
    public void FullSettingsJsonRoundTrip()
    {
        var settings = new OpenPatronAppSettings
        {
            PageType = OpenPatronPageType.Personal,
            PageTypeConfirmed = true,
            PageLayout =
            [
                new() { Id = "b1", Type = "profile-hero", Settings = JObject.FromObject(new { displayName = "Jane" }) },
                new() { Id = "b2", Type = "quick-support", Settings = JObject.FromObject(new { suggestedAmounts = new[] { 5, 15 } }) }
            ],
            Theme = new PageTheme { AccentColor = "#00ff00" },
            DefaultCurrency = "EUR",
            SupportMode = OpenPatronSupportMode.Both
        };

        var json = JsonConvert.SerializeObject(settings);
        var d = JsonConvert.DeserializeObject<OpenPatronAppSettings>(json)!;

        Assert.Equal(2, d.PageLayout!.Count);
        Assert.Equal("Jane", d.PageLayout[0].Settings!["displayName"]!.ToString());
        Assert.Equal("#00ff00", d.Theme!.AccentColor);
        Assert.Equal("EUR", d.DefaultCurrency);
    }

    [Fact]
    public void BlockListOrderPreservedThroughSerialization()
    {
        var blocks = new List<BlockDefinition>
        {
            new() { Id = "1", Type = "sponsor-wall" },
            new() { Id = "2", Type = "profile-hero" },
            new() { Id = "3", Type = "description" },
        };
        var json = JsonConvert.SerializeObject(blocks);
        var d = JsonConvert.DeserializeObject<List<BlockDefinition>>(json)!;
        Assert.Equal("sponsor-wall", d[0].Type);
        Assert.Equal("profile-hero", d[1].Type);
        Assert.Equal("description", d[2].Type);
    }

    // ── Offering resolver ──

    [Fact]
    public void OfferingResolverPrefersRicherOffering()
    {
        var richer = new OfferingData
        {
            Id = "rich", CreatedAt = new(2026, 4, 23, 20, 0, 0, System.TimeSpan.Zero),
            Plans = [new PlanData()], Features = []
        };
        var empty = new OfferingData
        {
            Id = "empty", CreatedAt = new(2026, 4, 23, 21, 0, 0, System.TimeSpan.Zero),
            Plans = [], Features = []
        };
        Assert.Equal("rich", OpenPatronOfferingResolver.SelectPreferredOffering([richer, empty], empty.Id)?.Id);
    }

    // ── Gravatar / MD5 (controller static helpers) ──

    [Fact]
    public void Md5HashIsCorrect()
    {
        Assert.Equal("5d41402abc4b2a76b9719d911017c592", UIOpenPatronController.ComputeMd5Hash("hello"));
    }

    [Fact]
    public void GravatarUrlNullForEmpty()
    {
        Assert.Null(UIOpenPatronController.ComputeGravatarUrl(null));
        Assert.Null(UIOpenPatronController.ComputeGravatarUrl(""));
    }
}
